variable "vpc_id" {}
variable "pub-sub1" {}
variable "pub-sub2" {}
variable "priv-sub1" {}
variable "priv-sub2" {}
variable "fargate_cpu" {}
variable "fargate_memory" {}
variable "app_count" {}
variable "elearning_certificate_arn" {}
variable "eaz1" {}
variable "eaz2" {}